### ISSUE TITLE
RHEL-09-652025: rsyslog.d find match incorrect

### ISSUE THREAD

**Issue by PrymalInstynct** [ansible-lockdown/RHEL9-STIG#2]
**Describe the Issue**
When the tasks for applying RHEL-09-652025 to files in /etc/rsyslog.d/ the task fails if there are no files in this directory

**Expected Behavior**
Tasks skips if no files are found in /etc/rsyslog.d/

**Actual Behavior**
Task fails

**Control(s) Affected**
RHEL-09-652025

**Environment (please complete the following information):**

- branch being used: main
- Ansible Version: 2.16.2
- Host Python Version: Python 3.11.8
- Ansible Server Python Version: Python 3.11.8

**Additional Notes**
None

**Possible Solution**
I looked at a debug of the variable `rhel9stig_rsyslog_conf` and if the folder `/etc/rsyslog.d` exists on the system at all the find task will return a match of 1. So I changed `rhel9stig_rsyslog_conf.matched > 1` on line 180 of `RHEL9-STIG/tasks/Cat2/RHEL-09-65xxxx.yml` and the task skipped as expected.

**Comment by uk-bolly** [comment]
hi @PrymalInstynct 

Thank you for taking the time to raise this issue. I am currently adding it to a new branch ready for Pr in the next couple of days.

Many thanks

uk-bolly
