### ISSUE TITLE
Why set min_ansible_version: 2.15.1

### ISSUE THREAD

**Issue by PrymalInstynct** [ansible-lockdown/RHEL9-STIG#22]
**Question**
I am curious if there is a specific reason that the minimum version of ansible has been set to 2.15.1 when the current version of ansible-core in the RHEL9 repos is 2.14.14.

It makes using this role a bit more challenging for air-gapped environments where pulling in the PyPI package is more difficult then using Sync'd Red Hat repos that are approved by your AO.

**Comment by uk-bolly** [comment]
hi @PrymalInstynct 

Superb catch, that was in error. I have just confirmed and runs fine with ansible 2.12.x and python 3.11. I am creating a PR to put this back.
Thanks

uk-bolly

**Comment by uk-bolly** [comment]
Merged to main
many thanks

uk-bolly
