### ISSUE TITLE
RHEL-09-232250 & RHEL-09-232255 use undefined/wrong variables

### ISSUE THREAD

**Issue by Coconutcoo** [ansible-lockdown/RHEL9-STIG#31]
**Describe the Issue**
For RHEL-09-232250 at https://github.com/ansible-lockdown/RHEL9-STIG/blob/devel/tasks/Cat2/RHEL-09-23xxxx.yml#L1899, currently we log `rhel9stig_ungrouped_files_dirs_audit.stdout_lines`, however I get the following error;
```
TASK [/opt/RHEL9-STIG : MEDIUM | RHEL-09-232250 | WARN | All RHEL 9 local files and directories must have a valid group owner.] ***
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout_lines'. 'dict object' has no attribute 'stdout_lines'\n\nThe error appears to be in '/opt/RHEL9-STIG/tasks/Cat2/RHEL-09-23xxxx.yml': line 1896, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: \"MEDIUM | RHEL-09-232250 | WARN | All RHEL 9 local files and directories must have a valid group owner.\"\n      ^ here\n"}
```

For RHEL-09-232255 at https://github.com/ansible-lockdown/RHEL9-STIG/blob/devel/tasks/Cat2/RHEL-09-23xxxx.yml#L1945, currently we also log `rhel9stig_ungrouped_files_dirs_audit.stdout_lines`, however I get the following error;
```
TASK [/opt/RHEL9-STIG : MEDIUM | RHEL-09-232255 | WARN | All RHEL 9 local files and directories must have a valid owner.] ***
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout_lines'. 'dict object' has no attribute 'stdout_lines'\n\nThe error appears to be in '/opt/RHEL9-STIG/tasks/Cat2/RHEL-09-23xxxx.yml': line 1942, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: \"MEDIUM | RHEL-09-232255 | WARN | All RHEL 9 local files and directories must have a valid owner.\"\n      ^ here\n"}
```

**Expected Behavior**
In both cases, the debug should just print the list of matched files, the ungrouped ones for 232250 and the unowned ones for 232255.

**Actual Behavior**
In both cases, currently these tasks fail if they are enabled as stdout_lines doesn't exist on rhel9stig_ungrouped_files_dirs_audit. Also, if that is fixed to say `rhel9stig_ungrouped_files_dirs_audit.results`, for 232255 the variable is wrong and prints out the un*grouped* files, not the unowned ones.

**Control(s) Affected**
RHEL-09-232250
RHEL-09-232255

**Environment (please complete the following information):**

- branch being used: 1.2.0
- Ansible Version: 2.16
- Host Python Version: 3.9.18
- Ansible Server Python Version: 3.11.10
- Additional Details: 

**Additional Notes**
Anything additional goes here

**Possible Solution**
[variable.patch](https://github.com/user-attachments/files/17044000/variable.patch)

**Comment by uk-bolly** [comment]
hi @Coconutcoo 

Thank you for taking the time to raise this issue. This is a great catch.
I have added a solution in to the latest PR that addresses this.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @Coconutcoo 

Thank you for this issue, this has now been merged and we will close. Please feel free to reopen if you feel this has not been addressed?

Many thanks

uk-bolly
