### ISSUE TITLE
Is Ansible 2.15 actually required?

### ISSUE THREAD

**Issue by aaronlippold** [ansible-lockdown/RHEL9-STIG#33]
RedHat is still pinning to v2.14 of Ansible, this makes using the playbooks generally slightly more challenging. 

Is there a hard requirement for v2.15 of ansible-core on the playbooks in general or can the playbook be updated to use v2.14 so that we can easily use the vendor provided ansible in the RHEL ecosystem.

**Comment by uk-bolly** [comment]
hi @aaronlippold 

Thank you for raising this, this was reverted in devel a couple of months back. I will hopefully butting a new release to main later this week/early next week, which will put it back to 2.12. Which works as expected as well.

Kindest regards

uk-bolly

**Comment by aaronlippold** [comment]
Great to hear.

--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by uk-bolly** [comment]
Merged to main
many thanks

uk-bolly

**Comment by aaronlippold** [comment]
Wonderful. Thank you sir.

--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
