### ISSUE TITLE
Disabling one control using the sudoers file or pwquality file breaks others using that file

### ISSUE THREAD

**Issue by Coconutcoo** [ansible-lockdown/RHEL9-STIG#34]
**Describe the Issue**
When disabling a control, e.g. rhel_09_432015, the PRELIM task's condition now fails (https://github.com/ansible-lockdown/RHEL9-STIG/blob/main/tasks/prelim.yml#L230-L234) as the `when:` is an implicit "and".

This then breaks the other controls that also want to use the variable, e.g. "rhel9stig_sudoers_files", registered by that prelim task. 

**Expected Behavior**
Disabling one control would not affect others, unless they are explicitly labelled as a pre-req (as occurs here https://github.com/ansible-lockdown/RHEL9-STIG/blob/main/tasks/Cat2/RHEL-09-4xxxxx.yml#L883).

Only if I disable all controls that a prelim is needed for, should that prelim be disabled.

**Actual Behavior**
Disabling any control that's included in a "when" for a prelim (as these generally register the variables), breaks the other controls using that variable.

**Control(s) Affected**
    - rhel_09_432015
    - rhel_09_432020
    - rhel_09_432025
    - rhel_09_432030
    - rhel_09_611060
    - rhel_09_611065
    - rhel_09_611070

**Environment (please complete the following information):**

- branch being used: 1.2.0
- Ansible Version: 2.16
- Host Python Version: 3.9.18
- Ansible Server Python Version: 3.11.10
- Additional Details: 

**Additional Notes**
Anything additional goes here

**Possible Solution**
Use the format used by https://github.com/ansible-lockdown/RHEL9-STIG/blob/main/tasks/prelim.yml#L202-L211, and make the when into an explicit OR where the tasks aren't actually pre-requisites.

**Comment by uk-bolly** [comment]
hi @Coconutcoo 

Thank you for this issue, this has now been merged and we will close. Please feel free to reopen if you feel this has not been addressed?

Many thanks

uk-bolly
