### ISSUE TITLE
RHEL-09-231065 is causing / file system to be changed from xfs to nfs

### ISSUE THREAD

**Issue by layluke** [ansible-lockdown/RHEL9-STIG#40]
**Describe the Issue**
RHEL-09-231065 is causing / file system to be changed from xfs to nfs

**Expected Behavior**
Add "nodev" to nfs mounts and do not change anything else

**Actual Behavior**
changes / mountpoint from xfs to nfs

**Control(s) Affected**
RHEL-09-231065
Possibly also:
RHEL-09-231070
RHEL-09-231075

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.15.1
- Host Python Version: Python 3.11
- Ansible Server Python Version: Python 3.9
- Additional Details:

**Additional Notes**
This i causing the systems the run this control to not boot up properly.

**Possible Solution**
Only loop through mount points with the nfs fstype attribute

**Comment by uk-bolly** [comment]
hi @layluke 

Thank you for taking the time to raise these Issues and PRs. Looking through this the selectattr is set on the conditional, although the solution you have is much tidier.
Also you have stated XFS to nfs, i will try and setup another system to test as this should never change to xfs, it should have kept it to the filesystem type it is set for.
Many thanks as always

uk-bolly
