### ISSUE TITLE
Disa benchmark returns false positives for certain controls

### ISSUE THREAD

**Issue by layluke** [ansible-lockdown/RHEL9-STIG#47]
**Describe the Issue**
Due to some the way quotes are put in some of the tasks, quotes are transferred to the line in files.

The disa benchmark looks in these files for values without quotes, causing these control checks to fail. The OS respects these values quoted or not.

**Expected Behavior**
When utilizing the disa benchmark for scanning, these control come back as passed

**Actual Behavior**
disa benchmark returns failed results when these values are quoted

**Control(s) Affected**
RHEL-09-611065
RHEL-09-611070
RHEL-09-611075
RHEL-09-611090
RHEL-09-611095
RHEL-09-611100
RHEL-09-611105
RHEL-09-611110
RHEL-09-611115
RHEL-09-611120
RHEL-09-611125
RHEL-09-611130

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.15.11
- Host Python Version: 3.9.18
- Ansible Server Python Version: 3.9.18
- Additional Details:

**Additional Notes**
This is more of a problem with the provided benchmark not being flexible enough, but the fix to get these scan results to pass is pretty simple

**Possible Solution**
Instead of quoting just the variable in the "line:" value of the task, quote the entire line, this prevents the quotes from being transferred to the files being edited.

**Comment by uk-bolly** [comment]
hi @layluke 

Thank you again for raising this. I have been working on rhel9-stig myself recently to add further updates and improvements to both remediate and align the audit.
For this issue and PR i had noted the same and already included in the branch i was working on, apologies we have crossed over here. This has now caused a conflict in #48 as its no longer required.
Apologies for this confusion.

kindest regards

uk-bolly

**Comment by layluke** [comment]
No problem, will close the PR.
