### ISSUE TITLE
NFS controls cause autofs filesystems to be entered into /etc/fstab

### ISSUE THREAD

**Issue by layluke** [ansible-lockdown/RHEL9-STIG#49]
**Describe the Issue**
When using automounts, and running NFS controls dealing with mount options, ansible reads mounts from ansible_facts.mounts and adds all mounts to /etc/fstab, including locations to autofs files, which is not supposed to be in /etc/fstab

**Expected Behavior**
automounts not being added to the /etc/fstab, as these are handled separately

**Actual Behavior**
automount files being added to /etc/fstab

**Control(s) Affected**
RHEL-09-231060
RHEL-09-231065
RHEL-09-231070
RHEL-09-231075

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.15.11
- Host Python Version: 3.9.18
- Ansible Server Python Version: 3.9.18

**Additional Notes**
Anything additional goes here

**Possible Solution**
Exclude fstype autofs in nfs tasks loop

**Comment by uk-bolly** [comment]
hi @layluke 

Great catch and super improvement, always great to get feedback on items like this. There is only so many configurations we are able to test.
Your time and PR are gratefully appreciated.
The PR is now merged to devel.

Many thanks

uk-bolly
