### ISSUE TITLE
RHEL-09-651010 Does not notify handler when already installed

### ISSUE THREAD

**Issue by layluke** [ansible-lockdown/RHEL9-STIG#51]
**Describe the Issue**
When AIDE is already installed, task for RHEL-09-651010 will not notify handler to build AIDE DB

**Expected Behavior**
AIDE database is built while flushing handler if STIG control is true

**Actual Behavior**
AIDE is not built

**Control(s) Affected**
RHEL-09-651010

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.15.11
- Host Python Version: 3.9.18
- Ansible Server Python Version: 3.9.18

**Possible Solution**
Remove the line 
`    - "'aide' not in ansible_facts.packages"`
This will allow the aide db to be built via handler, whether aide is installed already or not

**Comment by uk-bolly** [comment]
hi @layluke 

Thanks again, this is a great thought and the PR has been merged. Great feedback as always.

Many thanks

uk-bolly
