### ISSUE TITLE
RHEL-09-654275 Handler fails if control disabled

### ISSUE THREAD

**Issue by PrymalInstynct** [ansible-lockdown/RHEL9-STIG#59]
**Describe the Issue**
If Auditd immutability is not set by `RHEL-09-654275` then `Auditd_immutable_check` handler fails

**Expected Behavior**
Handler runs without issue

**Actual Behavior**
Handler failed

**Control(s) Affected**
RHEL-09-654275

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.17.5
- Host Python Version: 3.9.18
- Ansible Server Python Version: 3.12.7
- Additional Details:

**Fatal Error**
```
RUNNING HANDLER [RHEL9-STIG : Auditd_immutable_check] ***************************************************************************************************
Sunday 03 November 2024  16:38:20 -0700 (0:00:02.883)       0:15:20.426 ******* 
fatal: [10.10.1.203]: FAILED! => {"changed": false, "cmd": "grep -c \"^-e 2\" /etc/audit/rules.d/audit.rules", "delta": "0:00:00.033238", "end": "2024-11-03 23:38:21.802212", "msg": "non-zero return code", "rc": 1, "start": "2024-11-03 23:38:21.768974", "stderr": "", "stderr_lines": [], "stdout": "0", "stdout_lines": ["0"]}
```

**Possible Solution**
Add conditional check that returns an OK output when `auditd_immutable_check.rc` is equal to 0 or 1

**Comment by uk-bolly** [comment]
hi @PrymalInstynct 

Thank you as always for the feedback, it really does help us to be able to extend and improve the product.
I have added a fix for this into a new branch Nov24_issues. If you find that helps?

many thanks

uk-bolly

**Comment by PrymalInstynct** [comment]
Your fix has addressed this issue successfully
